export interface Clienti {
  "idCliente":String,
    "ragioneSociale": String,
    "partitaIva":String,
    "emailCliente":String,
    "pec":String,
    "telefonoCliente":Number,
    "tipoCliente":String,
    "nomeContatto":String,
    "cognomeContatto":String,
    "emailContatto":String,
    "telefonoContatto":String,
    "viaUno":String,
    "civicoUno":Number,
    "localitaUno":String,
    "capUno":String,
    "comuneUno":String,
    "viaDue":String,
    "civicoDue":Number,
    "localitaDue":String,
    "capDue":String,
    "comuneDue":String,
    "dataInserimento":String,
    "ultimoContatto":String,
    "fatturatoAnnuale":Number,
  "fatture":any,
  "indirizzoSedeLegale": any,
  "civico":String,


}
